name: CI

on:
  create:
  push:
    branches: master
    paths:
      - '**.zig'
  pull_request:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: master
      - run: zig fmt --check *.zig

  test-in-memory:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: master

      - name: Install qemu
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        run: |
          sudo apt-get update -y && sudo apt-get install -y qemu-user-binfmt

      - name: Ensure Zig cache dirs exist
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          mkdir -p .zig-cache
          mkdir -p .zig-cache/tmp
          mkdir -p .zig-global-cache
          mkdir -p .zig-global-cache/tmp

      - name: Ensure Zig cache dirs exist
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force .zig-cache | Out-Null
          New-Item -ItemType Directory -Force .zig-cache/tmp | Out-Null
          New-Item -ItemType Directory -Force .zig-global-cache | Out-Null
          New-Item -ItemType Directory -Force .zig-global-cache/tmp | Out-Null

      - name: Run Tests in memory
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        env:
          ZIG_LOCAL_CACHE_DIR: ${{ github.workspace }}/.zig-cache
          ZIG_GLOBAL_CACHE_DIR: ${{ github.workspace }}/.zig-global-cache
        run: zig build test -Dci=true -Din_memory=true --summary all -fqemu -fwine
      - name: Run Tests in memory
        if: ${{ matrix.os != 'ubuntu-24.04' }}
        env:
          ZIG_LOCAL_CACHE_DIR: ${{ github.workspace }}/.zig-cache
          ZIG_GLOBAL_CACHE_DIR: ${{ github.workspace }}/.zig-global-cache
        run: zig build test -Dci=true -Din_memory=true --summary all
